name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os:
          - linux
          - windows
        arch:
          - amd64

    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: GOOS=${{matrix.os}} GOARCH=${{matrix.arch}} go build -v .

      - name: Upload ${{matrix.os}} ${{matrix.arch}} binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.os}} ${{matrix.arch} binaries
          path: |
            iw6x-zero.*

